manifest-version = 1

[component]
name = "woopra-component"
version = "1.0.0"

category = "data-collection"
subcategory = "analytics"
documentation = "https://www.edgee.cloud/docs/components/data-collection/woopra"
repository = "https://github.com/edgee-cloud/woopra-component"
language = "Rust"
wit-version = "1.0.0"
icon-path = "woopra-icon.png"
description = '''
This component enables seamless integration between [Edgee](https://www.edgee.cloud)
and [Woopra](https://www.woopra.com/),
allowing you to collect and forward analytics events to your Woopra project.
'''

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && mv ./target/wasm32-wasip2/release/woopra_component.wasm ./woopra.wasm"
output_path = "woopra.wasm"

[component.settings.project_name]
title = "Project Name"
type = "string"
description = "Your Woopra Project Name (e.g. 'mywebsite.com')"
required = true
