manifest-version = 1

[component]
name = "Woopra"
version = "1.0.0"

category = "data-collection"
subcategory = "analytics"
documentation = "https://www.edgee.cloud/docs/components/data-collection/woopra"
repository = "https://github.com/edgee-cloud/woopra-component"
language = "Rust"
wit-version = "1.0.0"
icon-path = "woopra-icon.png"
description = '''
## Overview

The **Woopra** component by Edgee enables seamless integration of Woopra's customer journey analytics into your Edgee projects.
This component allows you to collect and forward analytics events to your Woopra project directly from the edge, enhancing performance and privacy by eliminating the need to load the Woopra script on your website.

---

## Key Features & Benefits

### Features

- **Edge Deployment**: Collects and forwards analytics events from the edge, reducing latency and improving performance.
- **Event Mapping**:
  - `Page` → `pv` (Page View)
  - `Track` → Custom event name
  - `User` → User identification
- **Privacy-Focused**: No third-party script needed—better privacy and compliance.
- **Easy Integration**: Plug-and-play setup with existing Edgee flows.

### Benefits

- **Faster Load Times**: No client-side scripts to slow down your page.
- **Improved Tracking Performance**: Edge-native event handling.
- **Simple Setup**: Minimal configuration needed.
- **Privacy by Design**: Aligns with GDPR, CCPA, and modern data handling policies.

---

## Use Cases

- **Full-Funnel Customer Insight**: Map out user journeys from first contact to retention.
- **Performance-First Analytics**: Get rich insights without adding JS bloat.
- **Ad Blocker Resistance**: Ensure consistent tracking even with blockers enabled.
- **Privacy and Compliance**: Comply with user consent and privacy preferences.
- **Unified Analytics Stack**: Sync behavioral data across tools using Woopra's integrations.

---

Additional resources: [Woopra](https://www.woopra.com/)
'''

[component.build]
command = "cargo build --target wasm32-wasip2 --release --target-dir ./target && rm -f ./woopra.wasm && mv ./target/wasm32-wasip2/release/woopra_component.wasm ./woopra.wasm"
output_path = "woopra.wasm"

[component.settings.project_name]
title = "Project Name"
type = "string"
description = "Your Woopra Project Name (e.g. 'mywebsite.com')"
required = true
